version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/aitdir/application
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: aituser
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: aituser
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: aituser
