name: Test Deployment

on:
  push:
    branches:
      - main

jobs:
  staging-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip
          sync; echo 3 | sudo tee /proc/sys/vm/drop_caches && free -h

      - name: Zip files
        run: |
          zip -r build.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build.zip
          path: build.zip

  staging-deploy:
    runs-on: ubuntu-latest
    needs: staging-build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build.zip
          path: build.zip

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Push build to S3
        run: |
          aws deploy push --application-name Codedeploy-application \
          --s3-location s3://codedepo-s3/staging-build.zip \
          --region us-east-2

      - name: Create deployment in CodeDeploy
        run: |
          aws deploy create-deployment --application-name Codedeploy-application \
          --s3-location bucket=codedepo-s3,key=staging-build.zip,bundleType=zip \
          --deployment-group-name Codedeploy-DG \
          --deployment-config-name CodeDeployDefault.AllAtOnce
